baseURL = "https://dqpm26.github.io/"
languageCode = "en"
title = "DQPM Collaboration"

[params]
  description = "Dynamical Quasi-Particle Model for QGP"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 3
  [[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 4
